# Read the Docs config file

# required
version: 2

# OS, python version, other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt

# build in the docs/ directory with sphinx
sphinx:
  configuration: docs/conf.py

# optional build formats
#formats:
#  - pdf
#  - epub

# optional python requirements to build documentation
# this is for reproducible builds